version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    env_file:
    - .env
    volumes:
    - ${PWD}/data/postgres:/data/postgres
    ports:
      - '5432:5432'